---
driver:
  name: docker
  hostname: {{ cookiecutter.kitchen_formula }}.ci.local
  use_sudo: false

provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_version: latest
  require_chef: false
  log_level: error
  formula: {{ cookiecutter.kitchen_formula }}
  grains:
    noservices: {{ 'True' if cookiecutter.kitchen_driver =='docker' else 'False' }}
  state_top:
    base:
      "*":
        - {{ cookiecutter.kitchen_formula }}
  pillars:
    top.sls:
      base:
        "*":
          - {{ cookiecutter.kitchen_formula }}

verifier:
  name: {{ cookiecutter.kitchen_verifier }}
  sudo: true

{% if cookiecutter.kitchen_driver =='docker' %}
platforms:
  - name: <%=ENV['PLATFORM'] || 'ubuntu-xenial'%>
    driver_config:
      image: <%=ENV['PLATFORM'] || 'trevorj/salty-whales:xenial'%>
      platform: ubuntu

suites:
  {%- if cookiecutter.kitchen_suites == "" %}
  - name: default
  #  provisioner:
  #    pillars-from-files:
  #      {{ cookiecutter.kitchen_formula }}.sls: tests/pillar/default.sls
  {%- else %}
  {%- for suite in cookiecutter.kitchen_suites.split() %}

  - name: {{ suite }}
    provisioner:
      pillars-from-files:
        {{ cookiecutter.kitchen_formula }}.sls: tests/pillar/{{suite}}.sls
  {%- endfor %}
  {%- endif %}

{%- endif %}
# vim: ft=yaml sw=2 ts=2 sts=2 tw=125
